framework:
    messenger:
        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
