services:
    php:
        image: ghcr.io/iq2i/thot:main
        env_file:
            - .env.local
        environment:
            APP_SECRET: ${APP_SECRET}
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
        volumes:
            - ./credentials/:/app/credentials

    php-worker:
        image: ghcr.io/iq2i/thot:main
        env_file:
            - .env.local
        environment:
            APP_SECRET: ${APP_SECRET}
        command: [ 'bin/console', 'messenger:consume', 'async', '-vv', '--time-limit=300', '--limit=25', '--memory-limit=512M' ]
        depends_on:
            php:
                condition: service_healthy

    php-scheduler:
        image: ghcr.io/iq2i/thot:main
        env_file:
            - .env.local
        environment:
            APP_SECRET: ${APP_SECRET}
            RUN_MIGRATIONS: false
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
            MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
            MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
        command: [ 'bin/console', 'messenger:consume', 'scheduler_default', '-vv', '--time-limit=300', '--limit=25', '--memory-limit=512M' ]
        depends_on:
            php:
                condition: service_healthy

    meilisearch:
        environment:
            MEILI_SCHEDULE_SNAPSHOT: 86400